# This is a config for E2B sandbox template.
# You can use template ID (7zdl750h40cugrsefqpy) or template name (juliusbiascan-dev) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("juliusbiascan-dev") # Sync sandbox
# sandbox = await AsyncSandbox.create("juliusbiascan-dev") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('juliusbiascan-dev')

team_id = "fdcb5f5d-a49b-4f8d-be21-b5a83b5eac86"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "juliusbiascan-dev"
template_id = "7zdl750h40cugrsefqpy"
